[project]
name = "migrations"
version = "0.0.1"
dependencies = [
    "aiogram-i18n==1.4",
    "alembic==1.17.1",
    "asyncpg==0.30.0",
    "msgspec==0.19.0",
    "pydantic-settings==2.11.0",
    "redis[hiredis]==7.0.1",
    "sqlalchemy==2.0.44",
]

[tool.uv]
package = false
